"""Frozen benchmark inputs and paper-pipeline contract versions."""

from __future__ import annotations

from pathlib import Path


FROZEN_BENCHMARK_SCHEMA_VERSION = "2.0.0"
FROZEN_BENCHMARK_VERSION = "2.0.0"
FROZEN_SCIENTIFIC_PAYLOAD_HASH = (
    "sha256:1a9969d31f80198f73c008eb78cdba70cb4411570345f0829552da4bcda87db9"
)
FROZEN_BENCHMARK_CONTENT_HASH = (
    "sha256:a315b54f934bb3b37e8273a9a766d5c87bd494089d99d7e82b6920b782e8ad57"
)
FROZEN_BENCHMARK_PATH = (
    Path(__file__).resolve().parent
    / "benchmarks"
    / "exoplanet_host_star"
    / "paper-reasoning-benchmark.json"
)

PRODUCER_NAME = "xingwen.paper_collection"
PRODUCER_VERSION = "1.0.0"
QUERY_NORMALIZATION_VERSION = "1.0.0"
CANONICALIZATION_VERSION = "1.0.0"
DEDUPE_VERSION = "1.0.0"
RANKING_VERSION = "1.0.0"
SELECTION_VERSION = "1.0.0"
RETRY_POLICY_VERSION = "1.0.0"
SOURCE_POLICY_VERSION = "1.0.0"
CROSSREF_ADAPTER_VERSION = "1.0.0"
SUMMARY_PRODUCER_NAME = "xingwen.paper_summary"
SUMMARY_PRODUCER_VERSION = "1.0.0"
SUMMARY_PARAMETERS_VERSION = "1.0.0"
CLAIM_PRODUCER_NAME = "xingwen.literature_claim"
CLAIM_PRODUCER_VERSION = "1.0.0"
CLAIM_SCHEMA_VERSION = "1.0.0"
CLAIM_PARAMETERS_VERSION = "1.0.0"
CLAIM_NORMALIZATION_VERSION = "1.0.0"
RELATION_PRODUCER_NAME = "xingwen.literature_relation"
RELATION_PRODUCER_VERSION = "1.0.0"
RELATION_ADJUDICATION_PRODUCER_NAME = "xingwen.literature_relation_adjudication"
RELATION_ADJUDICATION_PRODUCER_VERSION = "1.0.0"
RELATION_SCHEMA_VERSION = "1.0.0"
RELATION_PARAMETERS_VERSION = "1.0.0"
RELATION_PAIRING_VERSION = "1.0.0"
RELATION_COMPARISON_POLICY_VERSION = "1.0.0"
RELATION_TRACE_PROTOCOL_VERSION = "1.0.0"
RELATION_CONFIDENCE_DEFINITION_ID = "relation_classification_decision_confidence"
RELATION_CONFIDENCE_DEFINITION_VERSION = "1.0.0"
RELATION_CONFIDENCE_CALIBRATION_ID = (
    "exoplanet_host_star.paper_reasoning.relation_labels"
)
RELATION_CONFIDENCE_CALIBRATION_VERSION = FROZEN_BENCHMARK_VERSION
RELATION_CONFIDENCE_CALIBRATION_METHOD = "frozen_approved_label_reference"
RELATION_CONFIDENCE_CALIBRATION_SAMPLE_SIZE = 4
RELATION_CONFIDENCE_APPLICABILITY_SCOPE = (
    "benchmark.exoplanet_host_star.relation_admission_regression"
)
RELATION_CONFIDENCE_ACCEPTANCE_THRESHOLD = 0.9

# Open year bounds applied when a contract leaves the publication window
# unrestricted; NormalizedPaperQuery requires explicit year boundaries.
OPEN_YEAR_FROM = 1900
OPEN_YEAR_TO = 2100
