"""Deterministic A-05 demo fixture built by the real D-02 pipeline.

This module exists so the frontend paper-acquisition Fixture is generated by
the authoritative Python contract chain instead of being hand-written in
TypeScript. It drives the real ``PaperCollectionPipeline`` (frozen benchmark,
query normalization, canonicalization, dedupe, ranking and hashing) with a
deterministic in-process source adapter, then projects the result through the
same read shapes B-06 serves (``PaperCollectionRead`` and
``PaperCollectionCandidateRead``).

The records are demo review material: the four frozen expected papers of the
``search.tess_mission_and_catalogs`` scenario (seed papers whose
``intended_uses`` include ``fixture``) plus three clearly synthetic records
that exercise duplicate, uncertain-match and low-relevance review paths. All
hashes, identifiers, ranking and selection reasons come from the real
pipeline; nothing scientific is fabricated beyond the labelled demo records.

Regenerate the committed JSON with:

    uv run --project apps/api python -m services.paper_pipeline.demo_fixture
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from app.schemas._hashing import compute_canonical_payload_hash
from app.schemas.enums import PaperDataLevel, SourceMode
from app.schemas.evidence import SourceSnapshotRecord
from app.schemas.paper_collection import NormalizedPaperQuery, PaperCollection, PaperSourcePage
from app.schemas.paper_collection_api import (
    PaperCollectionCandidateRead,
    PaperCollectionRead,
)
from app.schemas.v2 import (
    EvidenceDetail,
    ProducerExecutionDetail,
    ProducerReference,
    SourceSnapshotDetail,
)

from .pipeline import PaperCollectionPipeline
from .sources.base import RawSourceRecord, SourceSearchResult

DEMO_SCENARIO_ID = "search.tess_mission_and_catalogs"
DEMO_PAGE_SIZE = 5
DEMO_SELECTION_LIMIT = 3

_BASE_TIME = datetime(2026, 7, 21, 8, 24, tzinfo=timezone.utc)
_RETRIEVED_AT = datetime(2026, 7, 21, 8, 24, 30, tzinfo=timezone.utc)

_ARTIFACT_VERSION_ID = "artv_papcol_01"
_ARTIFACT_ID = "art_papcol_01"
_PROJECT_ID = "proj_01JEXAMPLE"
_RUN_ID = "run_01JEXAMPLE"
_SNAPSHOT_DETAIL_ID = "snap_paper_crossref_01"

PROVENANCE_NOTE = (
    "Demo Replay fixture generated by the real D-02 PaperCollectionPipeline "
    f"against the frozen benchmark scenario {DEMO_SCENARIO_ID}. The four "
    "expected seed papers are real frozen bibliographic records; the three "
    "extra records are clearly synthetic review material (duplicate, "
    "uncertain match, low relevance). This is not a live paper search."
)

# Four real frozen seed papers (expected by the scenario) plus three labelled
# synthetic review records. Everything below flows through the real pipeline.
_DEMO_RECORDS: tuple[RawSourceRecord, ...] = (
    RawSourceRecord(
        source_id="crossref",
        source_record_id="crossref:10.1117/1.JATIS.1.1.014003",
        title="Transiting Exoplanet Survey Satellite",
        authors=("George R. Ricker", "Joshua N. Winn", "Roland Vanderspek"),
        year=2015,
        doi="10.1117/1.JATIS.1.1.014003",
        arxiv_id="1406.0151",
        url="https://doi.org/10.1117/1.JATIS.1.1.014003",
    ),
    RawSourceRecord(
        source_id="crossref",
        source_record_id="crossref:10.3847/1538-3881/aad050",
        title="The TESS Input Catalog and Candidate Target List",
        authors=("Keivan G. Stassun", "Ryan J. Oelkers", "Joshua Pepper"),
        year=2018,
        doi="10.3847/1538-3881/aad050",
        arxiv_id="1706.00495",
        url="https://doi.org/10.3847/1538-3881/aad050",
    ),
    RawSourceRecord(
        source_id="crossref",
        source_record_id="crossref:10.3847/1538-3881/ab3467",
        title="The Revised TESS Input Catalog and Candidate Target List",
        authors=("Keivan G. Stassun", "Ryan J. Oelkers", "Martin Paegert"),
        year=2019,
        doi="10.3847/1538-3881/ab3467",
        arxiv_id="1905.10694",
        url="https://doi.org/10.3847/1538-3881/ab3467",
    ),
    RawSourceRecord(
        source_id="crossref",
        source_record_id="crossref:10.3847/1538-4365/abefe1",
        title="The TESS Objects of Interest Catalog from the TESS Prime Mission",
        authors=("Natalia M. Guerrero", "Sara Seager", "Chelsea X. Huang"),
        year=2021,
        doi="10.3847/1538-4365/abefe1",
        arxiv_id="2103.12538",
        url="https://doi.org/10.3847/1538-4365/abefe1",
    ),
    # Synthetic duplicate of the TOI catalog record: same DOI through a second
    # aggregator entry with a shortened title (doi_exact group + title conflict).
    RawSourceRecord(
        source_id="crossref",
        source_record_id="crossref:demo-duplicate-toi-catalog",
        title="TESS Objects of Interest Catalog from the TESS Prime Mission",
        authors=("Natalia M. Guerrero", "Sara Seager"),
        year=2021,
        doi="10.3847/1538-4365/abefe1",
        arxiv_id=None,
        url="https://doi.org/10.3847/1538-4365/abefe1",
    ),
    # Synthetic uncertain match: same title/year as the mission paper but a
    # disjoint author list and no identifier (potential duplicate, uncertain).
    RawSourceRecord(
        source_id="crossref",
        source_record_id="crossref:demo-uncertain-mission-reprint",
        title="Transiting Exoplanet Survey Satellite",
        authors=("Anonymous Compiler",),
        year=2015,
        doi=None,
        arxiv_id=None,
        url="https://example.org/reprints/tess-mission",
    ),
    # Synthetic low-relevance record with a non-http(s) link, exercising the
    # exclusion reason and the unsafe external URL review path.
    RawSourceRecord(
        source_id="crossref",
        source_record_id="crossref:demo-unrelated-flares",
        title="A Survey of Unrelated M-dwarf Flares",
        authors=("D. Surveyor",),
        year=2019,
        doi=None,
        arxiv_id=None,
        url="ftp://mirror.example.org/flares.pdf",
    ),
)


class DemoSourceAdapter:
    """Deterministic crossref-shaped adapter for the demo fixture build."""

    source_id = "crossref"
    adapter_name = "crossref_demo_fixture"
    adapter_version = "1.0.0"

    def __init__(
        self,
        records: tuple[RawSourceRecord, ...] = _DEMO_RECORDS,
        *,
        retrieved_at: datetime = _RETRIEVED_AT,
    ) -> None:
        self.records = records
        self.retrieved_at = retrieved_at

    def search(
        self,
        query: NormalizedPaperQuery,
        *,
        source_mode: SourceMode,
        data_level: PaperDataLevel,
    ) -> SourceSearchResult:
        page_size = query.pagination.page_size
        record_payload = [record.hash_payload() for record in self.records]
        pages: list[PaperSourcePage] = []
        for page_number in range(1, len(self.records) // page_size + 2):
            offset = (page_number - 1) * page_size
            page_records = record_payload[offset : offset + page_size]
            if not page_records and page_number > 1:
                break
            pages.append(
                PaperSourcePage(
                    page_number=page_number,
                    offset=offset,
                    requested_rows=page_size,
                    returned_rows=len(page_records),
                    total_results=len(self.records),
                    attempt_count=1,
                    status_code=200,
                    retrieved_at=self.retrieved_at,
                    request_hash=compute_canonical_payload_hash(
                        {"query_hash": query.query_hash, "page": page_number}
                    ),
                    response_hash=compute_canonical_payload_hash(page_records),
                )
            )
        content_hash = compute_canonical_payload_hash(
            {"query_hash": query.query_hash, "records": record_payload}
        )
        snapshot = SourceSnapshotRecord(
            snapshot_id=f"snapshot.crossref.{content_hash[-24:]}",
            source_id=self.source_id,
            source_type="paper_metadata",
            retrieved_at=self.retrieved_at,
            query=query.normalized_query_string,
            query_hash=query.query_hash,
            content_hash=content_hash,
            license_note=(
                "Demo fixture containing public bibliographic metadata and "
                "labelled synthetic review records only."
            ),
            request_metadata={
                "adapter_name": self.adapter_name,
                "data_level": data_level.value,
                "demo_note": "deterministic demo fixture; not a live retrieval",
            },
        )
        return SourceSearchResult(
            records=self.records,
            pages=tuple(pages),
            snapshot=snapshot,
            retry_count=0,
        )


def _ticking_clock(start: datetime = _BASE_TIME, step_seconds: int = 15):
    state = {"tick": 0}

    def clock() -> datetime:
        value = start + timedelta(seconds=step_seconds * state["tick"])
        state["tick"] += 1
        return value

    return clock


def build_demo_collection() -> PaperCollection:
    pipeline = PaperCollectionPipeline(
        adapter=DemoSourceAdapter(), clock=_ticking_clock()
    )
    return pipeline.run(
        scenario_id=DEMO_SCENARIO_ID,
        page_size=DEMO_PAGE_SIZE,
        selection_limit=DEMO_SELECTION_LIMIT,
        source_mode=SourceMode.fixture,
        data_level=PaperDataLevel.fixture,
        run_id=None,
    )


def build_demo_read() -> tuple[PaperCollectionRead, tuple[PaperCollectionCandidateRead, ...]]:
    """Project the pipeline output through the B-06 read shapes."""

    collection = build_demo_collection()
    content = collection.model_dump(mode="json", exclude_none=False)
    content_hash = compute_canonical_payload_hash(content)
    pipeline_snapshot = collection.source_snapshots[0]
    snapshot_detail = SourceSnapshotDetail(
        id=_SNAPSHOT_DETAIL_ID,
        source_id=pipeline_snapshot.source_id,
        source_type=pipeline_snapshot.source_type,
        retrieved_at=pipeline_snapshot.retrieved_at,
        query=pipeline_snapshot.query,
        query_hash=pipeline_snapshot.query_hash,
        source_version_or_etag=pipeline_snapshot.source_version_or_etag,
        content_hash=pipeline_snapshot.content_hash,
        license_note=pipeline_snapshot.license_note,
        cache_version=pipeline_snapshot.cache_version,
        request_metadata=pipeline_snapshot.request_metadata,
    )
    producer_execution = ProducerExecutionDetail(
        id="pexec_run_papcol_01",
        run_id=_RUN_ID,
        step_key="searching_papers",
        step_attempt_id="att_papcol_01",
        producer=ProducerReference(
            type="algorithm",
            name=collection.producer.producer_name,
            version=collection.producer.producer_version,
            parameters_hash=collection.producer.parameters_hash,
        ),
        parameters={},
        parameters_hash=collection.producer.parameters_hash,
        input_hash=collection.input_hash,
        output_hash=collection.output_hash,
        status="completed",
        started_at=collection.producer.started_at,
        finished_at=collection.producer.finished_at,
        latency_ms=collection.producer.latency_ms,
        error_code=None,
    )
    evidence = tuple(
        EvidenceDetail(
            id=f"evd_paper_{index + 1:02d}",
            artifact_version_id=_ARTIFACT_VERSION_ID,
            target_type="paper_candidate",
            target_id=candidate.candidate_id,
            evidence_type="paper_search",
            source_snapshot_id=_SNAPSHOT_DETAIL_ID,
            paper_id=candidate.canonical_paper_id,
            locator={
                "kind": "database_cell",
                "query_hash": collection.query.query_hash,
                "row_key": candidate.raw.source_record_id,
                "field": "paper.title",
            },
            quote_or_value=candidate.title,
            extraction_method="deterministic_parser",
            confidence=1.0,
            created_at=collection.acquisition_run.finished_at,
        )
        for index, candidate in enumerate(collection.candidates)
    )
    read = PaperCollectionRead(
        artifact_version_id=_ARTIFACT_VERSION_ID,
        artifact_id=_ARTIFACT_ID,
        project_id=_PROJECT_ID,
        source_mode=SourceMode.fixture,
        content_hash=content_hash,
        input_hash=collection.input_hash,
        created_at=collection.acquisition_run.finished_at,
        collection=collection,
        producer_execution=producer_execution,
        source_snapshots=(snapshot_detail,),
        evidence=evidence,
    )
    groups = {
        group.duplicate_group_id: group for group in collection.duplicate_groups
    }
    candidate_reads = tuple(
        PaperCollectionCandidateRead(
            candidate=candidate,
            duplicate_group=groups[candidate.duplicate_group_id],
            source_snapshot=snapshot_detail,
            evidence=tuple(
                item
                for item in evidence
                if item.target_id
                in {candidate.candidate_id, candidate.canonical_paper_id}
                and item.source_snapshot_id == snapshot_detail.id
            ),
        )
        for candidate in collection.candidates
    )
    return read, candidate_reads


def build_fixture_document() -> dict[str, Any]:
    read, candidate_reads = build_demo_read()
    return {
        "$generated": {
            "tool": "services.paper_pipeline.demo_fixture",
            "command": (
                "uv run --project apps/api python -m "
                "services.paper_pipeline.demo_fixture"
            ),
            "scenario_id": DEMO_SCENARIO_ID,
            "benchmark_id": read.collection.benchmark.benchmark_id,
            "benchmark_version": read.collection.benchmark.benchmark_version,
            "provenance_note": PROVENANCE_NOTE,
        },
        "read": read.model_dump(mode="json", exclude_none=False),
        "candidate_reads": [
            item.model_dump(mode="json", exclude_none=False)
            for item in candidate_reads
        ],
    }


FIXTURE_OUTPUT_PATH = (
    Path(__file__).resolve().parents[2]
    / "packages"
    / "data-access"
    / "src"
    / "fixture"
    / "paper-acquisition.fixture.json"
)


def main() -> None:
    document = build_fixture_document()
    FIXTURE_OUTPUT_PATH.write_text(
        json.dumps(document, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {FIXTURE_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
