"""Deterministic A-05 demo fixture built by the real D-02 pipeline.

This module exists so the frontend paper-acquisition Fixture is generated by
the authoritative Python contract chain instead of being hand-written in
TypeScript. It drives the real ``PaperCollectionPipeline`` (frozen benchmark,
query normalization, canonicalization, dedupe, ranking and hashing) with a
deterministic in-process source adapter, then projects the result through the
same read shapes B-06 serves (``PaperCollectionRead`` and
``PaperCollectionCandidateRead``).

Records are never hand-transcribed: the four expected papers of the
``search.tess_mission_and_catalogs`` scenario are derived programmatically
from the frozen benchmark seed papers (whose ``intended_uses`` must include
``fixture``), and the three synthetic review records (duplicate, uncertain
match, low relevance) carry an explicit per-record ``synthetic_note`` so a
reviewer can tell them apart candidate by candidate. All hashes, identifiers,
ranking and selection reasons come from the real pipeline.

Regenerate the committed JSON with:

    uv run --project apps/api python -m services.paper_pipeline.demo_fixture
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from app.schemas._hashing import compute_canonical_payload_hash
from app.schemas.enums import PaperDataLevel, SourceMode
from app.schemas.evidence import SourceSnapshotRecord
from app.schemas.paper_benchmark import BenchmarkPackage
from app.schemas.paper_collection import (
    NormalizedPaperQuery,
    PaperCollection,
    PaperSourcePage,
)
from app.schemas.paper_collection_api import (
    PaperCollectionCandidateRead,
    PaperCollectionRead,
)
from app.schemas.core import (
    ArtifactVersionDetail,
    EvidenceDetail,
    ProducerExecutionDetail,
    ProducerReference,
    SourceSnapshotDetail,
)

from .benchmark import load_frozen_benchmark
from .pipeline import PaperCollectionPipeline
from .sources.base import RawSourceRecord, SourceSearchResult

DEMO_SCENARIO_ID = "search.tess_mission_and_catalogs"
DEMO_SOURCE_ID = "crossref"
DEMO_PAGE_SIZE = 5
DEMO_SELECTION_LIMIT = 3

_BASE_TIME = datetime(2026, 7, 21, 8, 24, tzinfo=timezone.utc)
_RETRIEVED_AT = datetime(2026, 7, 21, 8, 24, 30, tzinfo=timezone.utc)

_ARTIFACT_VERSION_ID = "artv_papcol_01"
_ARTIFACT_ID = "art_papcol_01"
_PROJECT_ID = "proj_01JEXAMPLE"
_RUN_ID = "run_01JEXAMPLE"
_SNAPSHOT_DETAIL_ID = "snap_paper_crossref_01"

SYNTHETIC_DUPLICATE_NOTE = (
    "Synthetic demo record: second aggregator entry with the same DOI, "
    "created to exercise duplicate-group review. Not a real publication "
    "record."
)
SYNTHETIC_UNCERTAIN_NOTE = (
    "Synthetic demo record: same title/year as the mission paper with a "
    "disjoint author list, created to exercise uncertain-match review. Not "
    "a real publication record."
)
SYNTHETIC_LOW_RELEVANCE_NOTE = (
    "Synthetic demo record: off-topic entry with a non-http link, created "
    "to exercise low-relevance exclusion and unsafe-URL review. Not a real "
    "publication record."
)

PROVENANCE_NOTE = (
    "Demo Replay fixture generated by the real D-02 PaperCollectionPipeline "
    f"against the frozen benchmark scenario {DEMO_SCENARIO_ID}. The four "
    "expected seed papers are derived programmatically from the frozen "
    "benchmark package; the three extra records are synthetic review "
    "material and each carries an explicit per-record synthetic_note. This "
    "is not a live paper search."
)


def _seed_records(benchmark: BenchmarkPackage) -> tuple[RawSourceRecord, ...]:
    """Derive the expected-paper records from the frozen benchmark package."""

    scenario = next(
        item
        for item in benchmark.search_scenarios
        if item.scenario_id == DEMO_SCENARIO_ID
    )
    seeds_by_id = {paper.paper_id: paper for paper in benchmark.seed_papers}
    records: list[RawSourceRecord] = []
    for paper_id in scenario.expected_paper_ids:
        seed = seeds_by_id[paper_id]
        if "fixture" not in seed.intended_uses:
            raise ValueError(
                f"frozen seed paper {paper_id} does not permit fixture use"
            )
        if seed.doi is None:
            raise ValueError(f"frozen seed paper {paper_id} lacks a DOI")
        records.append(
            RawSourceRecord(
                source_id=DEMO_SOURCE_ID,
                source_record_id=f"crossref:{seed.doi}",
                title=seed.title,
                authors=tuple(seed.authors),
                year=seed.year,
                doi=seed.doi,
                arxiv_id=seed.arxiv_id,
                url=f"https://doi.org/{seed.doi}",
            )
        )
    return tuple(records)


def _synthetic_records(
    seeds: tuple[RawSourceRecord, ...],
) -> tuple[RawSourceRecord, ...]:
    """Three labelled synthetic review records anchored on real seeds."""

    toi_catalog = next(record for record in seeds if record.year == 2021)
    mission = next(record for record in seeds if record.year == 2015)
    duplicate_title = toi_catalog.title.removeprefix("The ")
    return (
        # Same DOI through a second aggregator entry with a shortened title
        # (doi_exact group + title conflict inside the group).
        RawSourceRecord(
            source_id=DEMO_SOURCE_ID,
            source_record_id="crossref:demo-duplicate-toi-catalog",
            title=duplicate_title,
            authors=tuple(toi_catalog.authors[:2]),
            year=toi_catalog.year,
            doi=toi_catalog.doi,
            arxiv_id=None,
            url=f"https://doi.org/{toi_catalog.doi}",
            synthetic_note=SYNTHETIC_DUPLICATE_NOTE,
        ),
        # Same title/year as the mission paper but a disjoint author list and
        # no identifier (potential duplicate, uncertain match).
        RawSourceRecord(
            source_id=DEMO_SOURCE_ID,
            source_record_id="crossref:demo-uncertain-mission-reprint",
            title=mission.title,
            authors=("Anonymous Compiler",),
            year=mission.year,
            doi=None,
            arxiv_id=None,
            url="https://example.org/reprints/tess-mission",
            synthetic_note=SYNTHETIC_UNCERTAIN_NOTE,
        ),
        # Low-relevance record with a non-http(s) link, exercising the
        # exclusion reason and the unsafe external URL review path.
        RawSourceRecord(
            source_id=DEMO_SOURCE_ID,
            source_record_id="crossref:demo-unrelated-flares",
            title="A Survey of Unrelated M-dwarf Flares",
            authors=("D. Surveyor",),
            year=2019,
            doi=None,
            arxiv_id=None,
            url="ftp://mirror.example.org/flares.pdf",
            synthetic_note=SYNTHETIC_LOW_RELEVANCE_NOTE,
        ),
    )


def build_demo_records(
    benchmark: BenchmarkPackage | None = None,
) -> tuple[RawSourceRecord, ...]:
    package = benchmark or load_frozen_benchmark()
    seeds = _seed_records(package)
    return seeds + _synthetic_records(seeds)


class DemoSourceAdapter:
    """Deterministic crossref-shaped adapter for the demo fixture build."""

    source_id = DEMO_SOURCE_ID
    adapter_name = "crossref_demo_fixture"
    adapter_version = "1.0.0"

    def __init__(
        self,
        records: tuple[RawSourceRecord, ...],
        *,
        retrieved_at: datetime = _RETRIEVED_AT,
    ) -> None:
        self.records = records
        self.retrieved_at = retrieved_at

    def search(
        self,
        query: NormalizedPaperQuery,
        *,
        source_mode: SourceMode,
        data_level: PaperDataLevel,
    ) -> SourceSearchResult:
        page_size = query.pagination.page_size
        record_payload = [record.hash_payload() for record in self.records]
        pages: list[PaperSourcePage] = []
        for page_number in range(1, len(self.records) // page_size + 2):
            offset = (page_number - 1) * page_size
            page_records = record_payload[offset : offset + page_size]
            if not page_records and page_number > 1:
                break
            pages.append(
                PaperSourcePage(
                    page_number=page_number,
                    offset=offset,
                    requested_rows=page_size,
                    returned_rows=len(page_records),
                    total_results=len(self.records),
                    attempt_count=1,
                    status_code=200,
                    retrieved_at=self.retrieved_at,
                    request_hash=compute_canonical_payload_hash(
                        {"query_hash": query.query_hash, "page": page_number}
                    ),
                    response_hash=compute_canonical_payload_hash(page_records),
                )
            )
        content_hash = compute_canonical_payload_hash(
            {"query_hash": query.query_hash, "records": record_payload}
        )
        snapshot = SourceSnapshotRecord(
            snapshot_id=f"snapshot.crossref.{content_hash[-24:]}",
            source_id=self.source_id,
            source_type="paper_metadata",
            retrieved_at=self.retrieved_at,
            query=query.normalized_query_string,
            query_hash=query.query_hash,
            content_hash=content_hash,
            license_note=(
                "Demo fixture containing public bibliographic metadata and "
                "labelled synthetic review records only."
            ),
            request_metadata={
                "adapter_name": self.adapter_name,
                "data_level": data_level.value,
                "demo_note": "deterministic demo fixture; not a live retrieval",
            },
        )
        return SourceSearchResult(
            records=self.records,
            pages=tuple(pages),
            snapshot=snapshot,
            retry_count=0,
        )


def _ticking_clock(start: datetime = _BASE_TIME, step_seconds: int = 15):
    state = {"tick": 0}

    def clock() -> datetime:
        value = start + timedelta(seconds=step_seconds * state["tick"])
        state["tick"] += 1
        return value

    return clock


def build_demo_collection() -> PaperCollection:
    benchmark = load_frozen_benchmark()
    pipeline = PaperCollectionPipeline(
        benchmark=benchmark,
        adapter=DemoSourceAdapter(build_demo_records(benchmark)),
        clock=_ticking_clock(),
    )
    return pipeline.run(
        scenario_id=DEMO_SCENARIO_ID,
        page_size=DEMO_PAGE_SIZE,
        selection_limit=DEMO_SELECTION_LIMIT,
        source_mode=SourceMode.fixture,
        data_level=PaperDataLevel.fixture,
        run_id=None,
    )


def build_demo_read() -> tuple[PaperCollectionRead, tuple[PaperCollectionCandidateRead, ...]]:
    """Project the pipeline output through the B-06 read shapes."""

    collection = build_demo_collection()
    content = collection.model_dump(mode="json", exclude_none=False)
    content_hash = compute_canonical_payload_hash(content)
    pipeline_snapshot = collection.source_snapshots[0]
    snapshot_detail = SourceSnapshotDetail(
        id=_SNAPSHOT_DETAIL_ID,
        source_id=pipeline_snapshot.source_id,
        source_type=pipeline_snapshot.source_type,
        retrieved_at=pipeline_snapshot.retrieved_at,
        query=pipeline_snapshot.query,
        query_hash=pipeline_snapshot.query_hash,
        source_version_or_etag=pipeline_snapshot.source_version_or_etag,
        content_hash=pipeline_snapshot.content_hash,
        license_note=pipeline_snapshot.license_note,
        cache_version=pipeline_snapshot.cache_version,
        request_metadata=pipeline_snapshot.request_metadata,
    )
    producer_execution = ProducerExecutionDetail(
        id="pexec_run_papcol_01",
        run_id=_RUN_ID,
        step_key="searching_papers",
        step_attempt_id="att_papcol_01",
        producer=ProducerReference(
            type="algorithm",
            name=collection.producer.producer_name,
            version=collection.producer.producer_version,
            parameters_hash=collection.producer.parameters_hash,
        ),
        parameters={},
        parameters_hash=collection.producer.parameters_hash,
        input_hash=collection.input_hash,
        output_hash=collection.output_hash,
        status="completed",
        started_at=collection.producer.started_at,
        finished_at=collection.producer.finished_at,
        latency_ms=collection.producer.latency_ms,
        error_code=None,
    )
    evidence = tuple(
        EvidenceDetail(
            id=f"evd_paper_{index + 1:02d}",
            artifact_version_id=_ARTIFACT_VERSION_ID,
            target_type="paper_candidate",
            target_id=candidate.candidate_id,
            evidence_type="paper_search",
            source_snapshot_id=_SNAPSHOT_DETAIL_ID,
            paper_id=candidate.canonical_paper_id,
            locator={
                "kind": "database_cell",
                "query_hash": collection.query.query_hash,
                "row_key": candidate.raw.source_record_id,
                "field": "paper.title",
            },
            quote_or_value=candidate.title,
            extraction_method="deterministic_parser",
            confidence=1.0,
            created_at=collection.acquisition_run.finished_at,
        )
        for index, candidate in enumerate(collection.candidates)
    )
    read = PaperCollectionRead(
        artifact_version_id=_ARTIFACT_VERSION_ID,
        artifact_id=_ARTIFACT_ID,
        project_id=_PROJECT_ID,
        source_mode=SourceMode.fixture,
        content_hash=content_hash,
        input_hash=collection.input_hash,
        created_at=collection.acquisition_run.finished_at,
        collection=collection,
        producer_execution=producer_execution,
        source_snapshots=(snapshot_detail,),
        evidence=evidence,
    )
    groups = {
        group.duplicate_group_id: group for group in collection.duplicate_groups
    }
    candidate_reads = tuple(
        PaperCollectionCandidateRead(
            candidate=candidate,
            duplicate_group=groups[candidate.duplicate_group_id],
            source_snapshot=snapshot_detail,
            evidence=tuple(
                item
                for item in evidence
                if item.target_id
                in {candidate.candidate_id, candidate.canonical_paper_id}
                and item.source_snapshot_id == snapshot_detail.id
            ),
        )
        for candidate in collection.candidates
    )
    return read, candidate_reads


def build_fixture_document() -> dict[str, Any]:
    read, candidate_reads = build_demo_read()
    read_payload = read.model_dump(mode="json", exclude_none=False)
    version = ArtifactVersionDetail(
        id=read.artifact_version_id,
        artifact_id=read.artifact_id,
        project_id=read.project_id,
        created_by_run_id=_RUN_ID,
        version_number=1,
        schema_version=read.collection.schema_version,
        content=read_payload["collection"],
        content_hash=read.content_hash,
        input_hash=read.input_hash,
        source_mode=read.source_mode,
        producer=read.producer_execution.producer,
        source_snapshot_ids=tuple(item.id for item in read.source_snapshots),
        evidence_ids=tuple(item.id for item in read.evidence),
        supersedes_version_id=None,
        created_at=read.created_at,
        producer_execution=read.producer_execution,
        source_snapshots=read.source_snapshots,
        evidence=read.evidence,
    )
    return {
        "$generated": {
            "tool": "services.paper_pipeline.demo_fixture",
            "command": (
                "uv run --project apps/api python -m "
                "services.paper_pipeline.demo_fixture"
            ),
            "scenario_id": DEMO_SCENARIO_ID,
            "benchmark_id": read.collection.benchmark.benchmark_id,
            "benchmark_version": read.collection.benchmark.benchmark_version,
            "provenance_note": PROVENANCE_NOTE,
        },
        "read": read_payload,
        "candidate_reads": [
            item.model_dump(mode="json", exclude_none=False)
            for item in candidate_reads
        ],
        # The generic ArtifactVersion identity must be derived from the exact
        # same canonical PaperCollection dump: B-06 recomputes content_hash
        # over version.content and cross-checks schema/producer fields.
        "artifact_version": version.model_dump(mode="json", exclude_none=False),
    }


FIXTURE_OUTPUT_PATH = (
    Path(__file__).resolve().parents[2]
    / "packages"
    / "data-access"
    / "src"
    / "fixture"
    / "paper-acquisition.fixture.json"
)


def main() -> None:
    document = build_fixture_document()
    FIXTURE_OUTPUT_PATH.write_text(
        json.dumps(document, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {FIXTURE_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
