"""Deterministic literature-summary demo fixture built by the production pipeline.

This module exists so the frontend paper-summary Fixture is generated by the
authoritative Python contract chain instead of being hand-written in
TypeScript. It reuses the deterministic Paper Acquisition Workspace ``build_demo_collection()`` as
the Paper Acquisition Pipeline provenance input, drives the real ``PaperSummaryPipeline.admit``
(prompt registry, parameter hashing, Evidence cross-checks against the real
collection candidate and SourceSnapshot, output hashing), then projects the
admitted ``PaperSummaryArtifactContent`` through the same read shape PaperSummary API
serves (``PaperSummaryRead``) plus the immutable ``ArtifactVersionDetail``.

Nothing is hand-transcribed: the summarized paper is the first selected,
non-synthetic candidate of the demo collection, and every Evidence quote is
derived from that candidate's raw bibliographic record. The model response is
a deterministic ``PaperSummaryModelOutput`` payload deliberately exercising
all three support statuses: supported statements verified against real
paper_metadata, one unsupported statement carrying no Evidence at all, and
one unverifiable paper_text statement whose source excerpt is unavailable.

Regenerate the committed JSON with:

    uv run --project apps/api python -m services.paper_pipeline.demo_summary_fixture
    pnpm prettier --write packages/data-access/src/fixture/paper-summary.fixture.json

The prettier pass is mandatory after every regeneration: this generator
writes plain ``json.dumps`` output, while the repo formatting gate
(`pnpm format:check`) collapses short arrays onto one line.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.schemas._hashing import compute_canonical_payload_hash
from app.schemas.enums import SourceMode
from app.schemas.paper_collection import PaperCollection, PaperCollectionCandidate
from app.schemas.paper_summary import (
    PaperSummaryAdmissionStatus,
    PaperSummaryArtifactContent,
    PaperSummaryEvidenceCandidate,
    PaperSummaryEvidenceLocator,
)
from app.schemas.paper_summary_api import PaperSummaryPaperMetadata, PaperSummaryRead
from app.schemas.core import (
    ArtifactVersionDetail,
    EvidenceDetail,
    ProducerExecutionDetail,
    ProducerReference,
    SourceSnapshotDetail,
)

from .demo_fixture import (
    DEMO_SCENARIO_ID,
    _ARTIFACT_VERSION_ID as _COLLECTION_ARTIFACT_VERSION_ID,
    _PROJECT_ID,
    _RUN_ID,
    build_demo_collection,
)
from .summary import PaperSummaryPipeline

# Inside the demo run window (T4 08:16 .. T9 08:30) at the
# `run.summarizing_papers` event time (T7), after the paper-collection
# version (~08:24) and clear of the fixture adapter's 09:00 clock base.
_SUMMARY_TIME = datetime(2026, 7, 21, 8, 25, tzinfo=timezone.utc)

_ARTIFACT_VERSION_ID = "artv_papsum_01"
_ARTIFACT_ID = "art_papsum_01"
_SNAPSHOT_DETAIL_ID = "snap_papsum_crossref_01"
_PRODUCER_EXECUTION_ID = "pexec_run_papsum_01"
_STEP_ATTEMPT_ID = "att_papsum_01"
_MODEL_NAME = "fixture-model"
_MODEL_PARAMETERS: dict[str, float | int] = {"temperature": 0, "top_p": 1}

SUMMARY_PROVENANCE_NOTE = (
    "Demo Replay fixture generated by the real PaperSummaryPipeline "
    "over the deterministic Paper Acquisition Workspace demo PaperCollection (frozen benchmark "
    f"scenario {DEMO_SCENARIO_ID}). The summarized paper is the first "
    "selected non-synthetic candidate; every Evidence quote is derived from "
    "that candidate's raw record. The model response is a deterministic "
    "fixture payload that deliberately exercises the supported, unsupported "
    "and unverifiable statuses. This is not a live model call."
)


def _select_demo_candidate(collection: PaperCollection) -> PaperCollectionCandidate:
    """Pick the summarized paper: first selected, non-synthetic candidate."""

    return next(
        candidate
        for candidate in collection.candidates
        if candidate.selected and candidate.raw.synthetic_note is None
    )


def build_demo_evidence_candidates(
    candidate: PaperCollectionCandidate,
) -> tuple[PaperSummaryEvidenceCandidate, ...]:
    """Evidence anchored on the real collection candidate and its snapshot.

    Three paper_metadata quotes equal the candidate's raw metadata values, so
    the pipeline verifies them as supported. The paper_text quote carries no
    accessible excerpt, so the pipeline must classify it unverifiable.
    """

    if (
        candidate.raw.url is None
        or candidate.raw.year is None
        or candidate.raw.doi is None
    ):
        raise ValueError("demo summary candidate must carry url, year and doi")
    anchor = {
        "paper_id": candidate.canonical_paper_id,
        "candidate_id": candidate.candidate_id,
        "source_id": candidate.raw.source_id,
        "source_record_id": candidate.raw.source_record_id,
        "source_snapshot_id": candidate.raw.source_snapshot_id,
    }
    return (
        PaperSummaryEvidenceCandidate(
            evidence_id="ev.goal_title",
            locator=PaperSummaryEvidenceLocator(
                kind="paper_metadata",
                source_url=candidate.raw.url,
                metadata_field="title",
            ),
            quote_or_value=candidate.raw.title,
            **anchor,
        ),
        PaperSummaryEvidenceCandidate(
            evidence_id="ev.dataset_year",
            locator=PaperSummaryEvidenceLocator(
                kind="paper_metadata",
                source_url=candidate.raw.url,
                metadata_field="year",
            ),
            quote_or_value=str(candidate.raw.year),
            **anchor,
        ),
        PaperSummaryEvidenceCandidate(
            evidence_id="ev.finding_doi",
            locator=PaperSummaryEvidenceLocator(
                kind="paper_metadata",
                source_url=candidate.raw.url,
                metadata_field="doi",
            ),
            quote_or_value=candidate.raw.doi,
            **anchor,
        ),
        # No accessible_excerpt: the real pipeline must not verify this quote
        # and has to admit it as unverifiable (evidence.source_text_unavailable).
        PaperSummaryEvidenceCandidate(
            evidence_id="ev.method_text",
            locator=PaperSummaryEvidenceLocator(
                kind="paper_text",
                source_url=candidate.raw.url,
                section="Methods",
                text_range="paragraph 2, sentences 1-3",
            ),
            quote_or_value=(
                "Stellar parameters are compiled from all-sky photometric "
                "catalogs and parallax measurements."
            ),
            accessible_excerpt=None,
            **anchor,
        ),
    )


def build_demo_model_response(candidate: PaperCollectionCandidate) -> str:
    """Deterministic PaperSummaryModelOutput JSON for the selected paper."""

    payload = {
        "background": {
            "section_kind": "background",
            "overview": {
                "statement_id": "stmt.background",
                "item_kind": "objective",
                "text": (
                    f"The paper delivers {candidate.raw.title} to prioritize "
                    "TESS targets."
                ),
                "evidence_ids": ["ev.goal_title"],
            },
            "items": [],
        },
        "methodology": {
            "section_kind": "methodology",
            "overview": None,
            "items": [
                {
                    "statement_id": "stmt.methodology.workflow",
                    "item_kind": "workflow_step",
                    "text": (
                        "The catalog compiles stellar parameters from photometric "
                        "catalogs and parallax measurements."
                    ),
                    "evidence_ids": ["ev.method_text"],
                }
            ],
        },
        "dataset": {
            "section_kind": "dataset",
            "overview": None,
            "items": [
                {
                    "statement_id": "stmt.dataset",
                    "item_kind": "dataset",
                    "text": (
                        "The catalog release analyzed here dates to "
                        f"{candidate.raw.year}."
                    ),
                    "evidence_ids": ["ev.dataset_year"],
                }
            ],
        },
        "experiments": {
            "section_kind": "experiments",
            "overview": None,
            "items": [
                {
                    "statement_id": "stmt.experiments.result_doi",
                    "item_kind": "result",
                    "text": (
                        "The published catalog is registered under DOI "
                        f"{candidate.raw.doi}."
                    ),
                    "evidence_ids": ["ev.finding_doi"],
                }
            ],
        },
        "discussion": {
            "section_kind": "discussion",
            "overview": None,
            "items": [],
        },
        "limitations": {
            "section_kind": "limitations",
            "overview": None,
            "items": [
                {
                    "statement_id": "stmt.limitations.unsupported",
                    "item_kind": "limitation",
                    "text": (
                        "The catalog is claimed to be complete for all dwarf "
                        "stars, without any cited evidence."
                    ),
                    "evidence_ids": [],
                }
            ],
        },
        "research_questions": {
            "section_kind": "research_questions",
            "overview": None,
            "items": [],
        },
        "evidence_ids": [
            "ev.dataset_year",
            "ev.finding_doi",
            "ev.goal_title",
            "ev.method_text",
        ],
    }
    return json.dumps(payload, ensure_ascii=False)


def _admit_demo_summary(
    collection: PaperCollection, candidate: PaperCollectionCandidate
) -> PaperSummaryArtifactContent:
    pipeline = PaperSummaryPipeline(clock=lambda: _SUMMARY_TIME)
    result = pipeline.admit(
        paper_collection=collection,
        paper_collection_version_id=_COLLECTION_ARTIFACT_VERSION_ID,
        paper_id=candidate.canonical_paper_id,
        model_response=build_demo_model_response(candidate),
        model_name=_MODEL_NAME,
        parameters=_MODEL_PARAMETERS,
        evidence_candidates=build_demo_evidence_candidates(candidate),
        run_id=None,
    )
    if (
        result.admission_status is not PaperSummaryAdmissionStatus.accepted
        or result.summary is None
    ):
        raise ValueError(
            "demo summary fixture must be accepted by the real pipeline: "
            f"{result.failure_stage}"
        )
    return result.summary


def build_demo_summary() -> PaperSummaryArtifactContent:
    """Run the real PaperSummary Pipeline admission against the real Paper Acquisition Workspace demo collection."""

    collection = build_demo_collection()
    return _admit_demo_summary(collection, _select_demo_candidate(collection))


def build_demo_summary_read() -> tuple[PaperSummaryRead, ArtifactVersionDetail]:
    """Project the admitted summary through the PaperSummary API read shape."""

    collection = build_demo_collection()
    candidate = _select_demo_candidate(collection)
    summary = _admit_demo_summary(collection, candidate)
    content = summary.model_dump(mode="json", exclude_none=False)
    content_hash = compute_canonical_payload_hash(content)
    pipeline_snapshot = collection.source_snapshots[0]
    reference = summary.input_versions.source_snapshots[0]
    if reference.source_snapshot_id != pipeline_snapshot.snapshot_id:
        raise ValueError("summary input snapshot does not match the collection")
    # PaperSummary API re-links summary snapshot references to persisted snapshots by the
    # (source_id, source_version_or_etag, content_hash) key, so the persisted
    # detail must pin the exact source_version the pipeline derived.
    snapshot_detail = SourceSnapshotDetail(
        id=_SNAPSHOT_DETAIL_ID,
        source_id=pipeline_snapshot.source_id,
        source_type=pipeline_snapshot.source_type,
        retrieved_at=pipeline_snapshot.retrieved_at,
        query=pipeline_snapshot.query,
        query_hash=pipeline_snapshot.query_hash,
        source_version_or_etag=reference.source_version,
        content_hash=pipeline_snapshot.content_hash,
        license_note=pipeline_snapshot.license_note,
        cache_version=pipeline_snapshot.cache_version,
        request_metadata=pipeline_snapshot.request_metadata,
    )
    producer = summary.producer
    producer_execution = ProducerExecutionDetail(
        id=_PRODUCER_EXECUTION_ID,
        run_id=_RUN_ID,
        step_key=producer.step_key,
        step_attempt_id=_STEP_ATTEMPT_ID,
        producer=ProducerReference(
            type=producer.producer_type,
            name=producer.producer_name,
            version=producer.producer_version,
            model_name=producer.model_name,
            prompt_name=producer.prompt_name,
            prompt_version=producer.prompt_version,
            prompt_hash=producer.prompt_hash,
            parameters_hash=producer.parameters_hash,
        ),
        parameters=dict(_MODEL_PARAMETERS),
        parameters_hash=producer.parameters_hash,
        input_hash=summary.input_hash,
        output_hash=content_hash,
        status="completed",
        started_at=producer.started_at,
        finished_at=producer.finished_at,
        latency_ms=producer.latency_ms,
        error_code=None,
    )
    # Each retained summary Evidence must be persisted exactly once as a
    # generic Evidence row targeting a statement that references it, with the
    # summary source_record_id inside the locator (PaperSummary API cross-link check).
    statement_by_evidence: dict[str, str] = {}
    for statement in summary.statements():
        for evidence_id in statement.evidence_ids:
            statement_by_evidence[evidence_id] = statement.statement_id
    evidence = tuple(
        EvidenceDetail(
            id=f"evd_papsum_{index + 1:02d}",
            artifact_version_id=_ARTIFACT_VERSION_ID,
            target_type="paper_summary",
            target_id=statement_by_evidence[item.evidence_id],
            evidence_type=item.locator.kind,
            source_snapshot_id=_SNAPSHOT_DETAIL_ID,
            paper_id=item.paper_id,
            locator={
                "kind": item.locator.kind,
                "summary_evidence_id": item.evidence_id,
                "source_record_id": item.source_record_id,
                "source_url": str(item.locator.source_url),
                **(
                    {"metadata_field": item.locator.metadata_field}
                    if item.locator.kind == "paper_metadata"
                    # The generic domain `PaperTextLocator` reads `range`;
                    # `text_range` exists only inside the summary schema.
                    else {
                        "section": item.locator.section,
                        "range": item.locator.text_range,
                    }
                ),
            },
            quote_or_value=item.quote_or_value,
            extraction_method="paper_summary",
            confidence=1.0,
            created_at=producer.finished_at,
        )
        for index, item in enumerate(summary.evidence)
    )
    read = PaperSummaryRead(
        artifact_version_id=_ARTIFACT_VERSION_ID,
        artifact_id=_ARTIFACT_ID,
        project_id=_PROJECT_ID,
        version_number=1,
        supersedes_version_id=None,
        source_mode=SourceMode.fixture,
        content_hash=content_hash,
        input_hash=summary.input_hash,
        created_at=producer.finished_at,
        paper=PaperSummaryPaperMetadata(
            paper_id=candidate.canonical_paper_id,
            title=candidate.title,
            authors=candidate.authors,
            year=candidate.year,
        ),
        summary=summary,
        cache_audits=(),
        producer_execution=producer_execution,
        source_snapshots=(snapshot_detail,),
        evidence=evidence,
    )
    # The generic ArtifactVersion identity must be derived from the exact
    # same canonical PaperSummary dump: PaperSummary API recomputes content_hash over
    # version.content and cross-checks schema/producer fields.
    version = ArtifactVersionDetail(
        id=_ARTIFACT_VERSION_ID,
        artifact_id=_ARTIFACT_ID,
        project_id=_PROJECT_ID,
        created_by_run_id=_RUN_ID,
        version_number=1,
        schema_version=summary.schema_version,
        content=content,
        content_hash=content_hash,
        input_hash=summary.input_hash,
        source_mode=SourceMode.fixture,
        producer=producer_execution.producer,
        source_snapshot_ids=(snapshot_detail.id,),
        evidence_ids=tuple(item.id for item in evidence),
        supersedes_version_id=None,
        created_at=producer.finished_at,
        producer_execution=producer_execution,
        source_snapshots=(snapshot_detail,),
        evidence=evidence,
    )
    return read, version


def build_summary_fixture_document() -> dict[str, Any]:
    read, version = build_demo_summary_read()
    return {
        "$generated": {
            "tool": "services.paper_pipeline.demo_summary_fixture",
            "command": (
                "uv run --project apps/api python -m "
                "services.paper_pipeline.demo_summary_fixture"
            ),
            "scenario_id": DEMO_SCENARIO_ID,
            "benchmark_id": read.summary.benchmark.benchmark_id,
            "benchmark_version": read.summary.benchmark.benchmark_version,
            "paper_id": read.summary.paper_id,
            "paper_collection_version_id": (
                read.summary.input_versions.paper_collection_version_id
            ),
            "provenance_note": SUMMARY_PROVENANCE_NOTE,
        },
        "read": read.model_dump(mode="json", exclude_none=False),
        "artifact_version": version.model_dump(mode="json", exclude_none=False),
    }


FIXTURE_OUTPUT_PATH = (
    Path(__file__).resolve().parents[2]
    / "packages"
    / "data-access"
    / "src"
    / "fixture"
    / "paper-summary.fixture.json"
)


def main() -> None:
    document = build_summary_fixture_document()
    FIXTURE_OUTPUT_PATH.write_text(
        json.dumps(document, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"wrote {FIXTURE_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
