"""Build the D-10 Golden Set manifest (reproducible, license-governed).

Produces ``golden_set.json`` describing 15-20 exoplanet_host_star entries. The
10 synthetic fixtures are committed to ``fixtures/`` and carry their content
hash. Restricted real papers are listed as ``local_only`` manifest entries
(source / DOI / license / provenance / expected annotation) but their PDFs are
NEVER committed (per D-10 #26). The report must always state Fixture != Golden
and Recorded != Live.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from app.schemas._hashing import compute_canonical_payload_hash
from app.schemas.scientific_document_benchmark import (
    BenchmarkDataType,
    GoldenSetEntry,
    GoldenSetManifest,
)

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
MANIFEST_PATH = Path(__file__).resolve().parent / "golden_set.json"


# (key, title, coverage_tags) for the committed synthetic fixtures.
_FIXTURE_SPECS = [
    ("born_digital", "Exoplanet Host-Star Integration Study", ("born-digital", "paragraph", "reading-order")),
    ("two_column", "Two-Column Hot-Jupiter Survey", ("two-column", "reading-order")),
    ("simple_table", "Sample Planet Parameters", ("table", "simple-table")),
    ("complex_table", "Stellar Parameters With Merged Header", ("table", "complex-table", "spans")),
    ("cross_page_table", "Cross-Page Table (split)", ("table", "cross-page", "partial")),
    ("formula", "Orbital Mechanics Relations", ("formula",)),
    ("figure_caption", "Radius-Period Distribution", ("figure", "caption")),
    ("mixed", "Mixed Text and Figure Layout", ("mixed", "figure", "caption")),
    ("scanned_like", "Archived Observation Note", ("scanned-like", "low-quality")),
    ("low_quality", "Preliminary Reduction", ("low-quality", "partial")),
]

# Restricted real papers (local-only; PDF not committed). Placeholder DOIs are
# illustrative identifiers for the exoplanet_host_star main case; the repository
# stores only provenance + license note + expected annotation, never the PDF.
_RESTRICTED_SPECS = [
    ("real_001", "WASP-12b host-star parameters", ("born-digital", "table", "formula"), "10.0000/wasp12.example", "local-only; PDF not redistributed"),
    ("real_002", "Kepler-7b stellar characterization", ("two-column", "figure"), "10.0000/kepler7.example", "local-only; arXiv preprint, check license"),
    ("real_003", "HAT-P-7 system transit analysis", ("formula", "table"), "10.0000/hatp7.example", "local-only; journal PDF behind paywall"),
    ("real_004", "TrES-2b equilibrium temperature", ("paragraph", "figure", "caption"), "10.0000/tres2.example", "local-only; author PDF"),
    ("real_005", "CoRoT-1b optical albedo", ("mixed", "low-quality"), "10.0000/corot1.example", "local-only; scanned archival scan"),
    ("real_006", "XO-3b eccentric orbit", ("cross-page", "table", "spans"), "10.0000/xo3.example", "local-only; multi-page table"),
]


def _content_hash_of_pdf(path: Path) -> str:
    data = path.read_bytes()
    return "sha256:" + hashlib.sha256(data).hexdigest()


def build_manifest() -> GoldenSetManifest:
    entries: list[GoldenSetEntry] = []
    for key, title, tags in _FIXTURE_SPECS:
        pdf = FIXTURES_DIR / f"golden_{key}.pdf"
        chash = _content_hash_of_pdf(pdf) if pdf.is_file() else None
        entries.append(
            GoldenSetEntry(
                entry_id=f"gs-{key}",
                case_key="exoplanet_host_star",
                title=title,
                data_type=BenchmarkDataType.fixture,
                source="synthetic-fixture",
                license_note="CC0 synthetic; generated by repo tooling, no third-party copyright",
                content_hash=chash,
                availability="committed-fixture",
                coverage_tags=tuple(tags),
                local_only=False,
            )
        )
    for key, title, tags, doi, lic in _RESTRICTED_SPECS:
        entries.append(
            GoldenSetEntry(
                entry_id=f"gs-{key}",
                case_key="exoplanet_host_star",
                title=title,
                data_type=BenchmarkDataType.golden,
                source="restricted-publication",
                doi_or_identifier=doi,
                license_note=lic,
                content_hash=None,
                availability="local-only",
                coverage_tags=tuple(tags),
                local_only=True,
            )
        )
    manifest = GoldenSetManifest(
        manifest_id="d10-golden-set",
        version="1.0.0",
        case_key="exoplanet_host_star",
        generated_at=datetime.now(timezone.utc).replace(microsecond=0),
        sample_count=len(entries),
        entries=tuple(entries),
        content_hash=_manifest_hash(entries),
    )
    return manifest


def _manifest_hash(entries: list[GoldenSetEntry]) -> str:
    payload = {
        "sample_count": len(entries),
        "entry_ids": sorted(e.entry_id for e in entries),
        "local_only": sorted(e.entry_id for e in entries if e.local_only),
    }
    return compute_canonical_payload_hash(payload)


def main() -> int:
    manifest = build_manifest()
    MANIFEST_PATH.write_text(
        manifest.model_dump_json(indent=2) + "\n", encoding="utf-8"
    )
    print(f"wrote {MANIFEST_PATH} with {manifest.sample_count} entries")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
