/**
 * Synchronises the B-15 generated `/api/v2` core contract into the frontend
 * `@xingwen/contracts` package.
 *
 * This script is the single bridge between the Python authoring source
 * (`apps/api/src/app/schemas/v2.py` → `packages/schemas/generated/v2-core/`)
 * and the frontend contract consumption boundary. It:
 *
 * 1. Vendors the standalone JSON Schema files and manifest so the frontend
 *    package is self-contained for `ajv` compilation.
 * 2. Generates TypeScript DTO types from the OpenAPI `components.schemas` so
 *    the frontend has compile-time types without hand-writing a second
 *    production schema (governance red line).
 *
 * Run via: `pnpm --filter @xingwen/contracts sync-contracts`
 *
 * Generated outputs are committed; a drift test in
 * `packages/contracts/src/validation.test.ts` guards against manual edits.
 */

import {
  copyFileSync,
  cpSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceDir = resolve(root, "packages/schemas/generated/v2-core");
const targetDir = resolve(root, "packages/contracts/src/generated/v2-core");

const BANNER = `/**
 * AUTO-GENERATED by scripts/sync_v2_contracts.mjs — DO NOT EDIT.
 *
 * Source: packages/schemas/generated/v2-core/openapi.json
 * Authoring source: apps/api/src/app/schemas/v2.py (Pydantic)
 *
 * These TypeScript types are the /api/v2 transport DTOs (snake_case). They are
 * generated from the B-15 frozen JSON Schemas so the frontend never maintains
 * a hand-written second production schema.
 *
 * To regenerate: pnpm --filter @xingwen/contracts sync-contracts
 */
`;

/** Rewrite OpenAPI `$ref` pointers to standard JSON Schema `$defs` pointers. */
function rewriteRefs(node) {
  if (node === null || typeof node !== "object") {
    return node;
  }
  if (Array.isArray(node)) {
    return node.map(rewriteRefs);
  }
  const result = {};
  for (const [key, value] of Object.entries(node)) {
    if (key === "$ref" && typeof value === "string") {
      result[key] = value.replace("#/components/schemas/", "#/$defs/");
    } else {
      result[key] = rewriteRefs(value);
    }
  }
  return result;
}

/**
 * Strip `title` annotations from schema nodes while preserving property names.
 *
 * Pydantic emits a `title` annotation on every property (e.g.
 * `"title": "Created At"`), which causes json-schema-to-typescript to generate
 * noisy single-use type aliases (`CreatedAt7`). This function removes `title`
 * annotations from schema nodes but keeps property names inside `properties`
 * objects (e.g. a property named `title` on `ResearchArtifact` is preserved).
 */
function stripTitleDeep(node) {
  if (node === null || typeof node !== "object") {
    return node;
  }
  if (Array.isArray(node)) {
    return node.map(stripTitleDeep);
  }
  const result = {};
  for (const [key, value] of Object.entries(node)) {
    if (
      key === "properties" &&
      typeof value === "object" &&
      value !== null &&
      !Array.isArray(value)
    ) {
      // Keep all property names; strip titles from each property's schema.
      const props = {};
      for (const [propName, propSchema] of Object.entries(value)) {
        props[propName] = stripTitleDeep(propSchema);
      }
      result[key] = props;
    } else if (key === "title") {
      // Skip title annotations on schema nodes.
      continue;
    } else {
      result[key] = stripTitleDeep(value);
    }
  }
  return result;
}

function stripPropertyTitles(schemas) {
  const cleaned = {};
  for (const [name, schema] of Object.entries(schemas)) {
    cleaned[name] = { ...stripTitleDeep(schema), title: name };
  }
  return cleaned;
}

async function vendorJsonSchemas() {
  const jsonTargetDir = resolve(targetDir, "json");
  mkdirSync(jsonTargetDir, { recursive: true });

  // Copy all .schema.json files.
  const sourceJsonDir = resolve(sourceDir, "json");
  cpSync(sourceJsonDir, jsonTargetDir, {
    recursive: true,
    filter: (src) => src.endsWith(".schema.json") || src === sourceJsonDir,
  });

  // Copy manifest.json.
  copyFileSync(
    resolve(sourceDir, "manifest.json"),
    resolve(targetDir, "manifest.json"),
  );

  console.log("Vendored v2-core JSON schemas and manifest.");
}

async function generateDtoTypes() {
  const openapiPath = resolve(sourceDir, "openapi.json");
  const openapi = JSON.parse(readFileSync(openapiPath, "utf8"));
  const schemas = rewriteRefs(openapi.components.schemas);
  const manifest = JSON.parse(
    readFileSync(resolve(sourceDir, "manifest.json"), "utf8"),
  );

  // A richer endpoint may inline a base Pydantic model through inheritance,
  // causing OpenAPI to omit that base as a standalone component. Preserve
  // every model promised by the checked-in manifest for existing consumers.
  for (const model of manifest.models) {
    if (schemas[model.name]) continue;
    const standalone = JSON.parse(
      readFileSync(resolve(sourceDir, model.path), "utf8"),
    );
    const { $defs = {}, ...rootSchema } = standalone;
    schemas[model.name] = rootSchema;
    for (const [name, schema] of Object.entries($defs)) {
      schemas[name] ??= schema;
    }
  }

  const normalizedSchemas = stripPropertyTitles(schemas);

  // Wrap all component schemas into a single root $defs block so
  // json-schema-to-typescript emits every definition exactly once.
  const megaSchema = {
    $id: "v2-core-contract",
    $schema: "http://json-schema.org/draft-07/schema#",
    type: "object",
    properties: {},
    $defs: normalizedSchemas,
  };

  const typescript = await compile(megaSchema, "V2CoreContractRoot", {
    unreachableDefinitions: true,
    additionalProperties: false,
    bannerComment: BANNER,
    cwd: targetDir,
    style: {
      semi: true,
      singleQuote: false,
      tabWidth: 2,
      trailingComma: "all",
      printWidth: 100,
    },
  });

  // Strip the empty root interface that compile() emits for the wrapper.
  const cleaned = typescript
    .replace(/export interface V2CoreContract\w*\s*\{\s*\}\s*/gu, "")
    .trimEnd();

  const dtoPath = resolve(targetDir, "dto.ts");
  writeFileSync(dtoPath, `${cleaned}\n`);
  console.log(`Generated ${dtoPath}`);
}

async function main() {
  mkdirSync(targetDir, { recursive: true });
  await vendorJsonSchemas();
  await generateDtoTypes();
  console.log("v2-core contract sync complete.");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
