"""Version-pinned inputs and stable logical identities for Versioned Evidence Graph."""

from .admission import GraphAdmissionFailure, build_integrity_report

from .identity import (
    GraphEdgeIdentity,
    GraphIdentityError,
    GraphNodeIdentity,
    GraphNodeVersionBinding,
    canonical_edge_order,
    canonical_evidence_use_order,
    canonical_node_order,
    claim_node_identity,
    dataset_node_identity,
    field_node_identity,
    graph_edge_type_for_literature_relation,
    graph_evidence_use_id,
    literature_relation_edge_identity,
    paper_node_identity,
    provides_field_edge_identity,
    research_goal_node_identity,
    supports_finding_edge_identity,
    uses_dataset_edge_identity,
)
from .ports import (
    EvidenceRestrictionFact,
    EvidenceRestrictionReadPort,
    GraphDataVersionSelection,
    GraphInputIntegrityError,
    GraphInputVersionSelection,
    PersistedEvidenceBinding,
    PersistedSourceSnapshotBinding,
    PipelineEvidenceBindingReadPort,
    PublishedArtifactVersionPins,
    PublishedDataGraphInputs,
    PublishedDatasetVersion,
    PublishedFieldDictionaryVersion,
    PublishedGraphInputs,
    PublishedLiteratureRelationsVersion,
    StoredPipelineEvidenceBinding,
    VersionedGraphInputReadPort,
)
from .pipeline import (
    GraphPipeline,
    build_complete_progressive_input,
    required_progressive_item_ids,
)

__all__ = [
    "EvidenceRestrictionFact",
    "EvidenceRestrictionReadPort",
    "GraphDataVersionSelection",
    "GraphAdmissionFailure",
    "GraphEdgeIdentity",
    "GraphIdentityError",
    "GraphInputIntegrityError",
    "GraphInputVersionSelection",
    "GraphNodeIdentity",
    "GraphNodeVersionBinding",
    "GraphPipeline",
    "PersistedEvidenceBinding",
    "PersistedSourceSnapshotBinding",
    "PipelineEvidenceBindingReadPort",
    "PublishedArtifactVersionPins",
    "PublishedDataGraphInputs",
    "PublishedDatasetVersion",
    "PublishedFieldDictionaryVersion",
    "PublishedGraphInputs",
    "PublishedLiteratureRelationsVersion",
    "StoredPipelineEvidenceBinding",
    "VersionedGraphInputReadPort",
    "build_complete_progressive_input",
    "build_integrity_report",
    "canonical_edge_order",
    "canonical_evidence_use_order",
    "canonical_node_order",
    "claim_node_identity",
    "dataset_node_identity",
    "field_node_identity",
    "graph_edge_type_for_literature_relation",
    "graph_evidence_use_id",
    "literature_relation_edge_identity",
    "paper_node_identity",
    "provides_field_edge_identity",
    "research_goal_node_identity",
    "required_progressive_item_ids",
    "supports_finding_edge_identity",
    "uses_dataset_edge_identity",
]
